name: Odoo Addon Generate Readme

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2
      with:
        persist-credentials: false 

    - uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Synchronize Repositories
      env:
        BOT_GITHUB_USER: ${{ secrets.BOT_GITHUB_USER }}
        BOT_GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: |
        git config --global user.email ${{ secrets.BOT_GITHUB_EMAIL }}
        git config --global user.name ${{ secrets.BOT_GITHUB_USER }}
        ./sync-repositories.py
